FROM drupaldocker/php:7.0-cli-2.x
MAINTAINER eiriksm <eirik@morland.no>
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

ARG COMPOSER_VERSION=1
ENV COMPOSER_VERSION=$COMPOSER_VERSION
ENV COMPOSER_DISCARD_CHANGES=1
ENV COMPOSER_MEMORY_LIMIT=-1
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV COMPOSER_PROCESS_TIMEOUT=1200

RUN composer self-update \
    && composer global require hirak/prestissimo \
    && apk add --no-cache imagemagick imagemagick-libs imagemagick-dev autoconf bzip2-dev g++ make icu-dev \
    && yes | pecl install apcu mongodb imagick \
    && docker-php-ext-configure intl --enable-intl \
    && docker-php-ext-install exif bz2 pcntl intl \
    && docker-php-ext-enable apcu intl mongodb imagick \
    && mkdir ~/.ssh/ \
    && composer install --no-dev --optimize-autoloader \
    && ssh-keyscan -t rsa,dsa git.drupal.org >> ~/.ssh/known_hosts \
    && ssh-keyscan -t rsa,dsa gitlab.com >> ~/.ssh/known_hosts \
    && ssh-keyscan -t rsa,dsa bitbucket.org >> ~/.ssh/known_hosts \
    && ssh-keyscan -t rsa,dsa github.com >> ~/.ssh/known_hosts \
    && git clone https://github.com/FriendsOfPHP/security-advisories /root/.symfony/cache/security-advisories \
    && git clone https://github.com/violinist-dev/drupal-contrib-sa /root/drupal-contrib-sa \
    && echo "DRUPAL_CONTRIB_SA_PATH=/root/drupal-contrib-sa" > /usr/src/myapp/.env \
    && wget https://get.symfony.com/cli/v4.5.4/symfony_linux_amd64 -O /tmp/symfony.gz \
    && gzip -d /tmp/symfony.gz \
    && chmod 755 /tmp/symfony \
    && mv /tmp/symfony /usr/local/bin/symfony \
    && rm -rf /usr/local/bin/composer \
    && cd /usr/src/myapp \
    && ./vendor/bin/composer require composer/composer:^$COMPOSER_VERSION --update-with-dependencies
CMD ["php", "runner.php"]
