FROM violinist/php-base:7.1-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN composer require bitbucket/client \
    && composer install --no-dev --optimize-autoloader \
    && rm -rf /usr/local/bin/composer

CMD ["php", "runner.php"]
