FROM drupaldocker/php:7.0-cli-2.x
MAINTAINER eiriksm <eirik@morland.no>
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN composer install --no-dev --optimize-autoloader \
    && composer global require hirak/prestissimo \
    && apk add --no-cache autoconf bzip2-dev g++ make icu-dev \
    && yes | pecl install apcu \
    && docker-php-ext-configure intl --enable-intl \
    && docker-php-ext-install bz2 pcntl intl \
    && docker-php-ext-enable apcu intl
RUN mkdir -p /root/.symfony/cache
RUN git clone https://github.com/FriendsOfPHP/security-advisories /root/.symfony/cache/security-advisories
RUN git clone https://github.com/violinist-dev/drupal-contrib-sa /tmp/drupal-contrib-sa \
    && cp -r /tmp/drupal-contrib-sa/sa_yaml/drupal/* /root/.symfony/cache/security-advisories/drupal/
RUN wget https://get.symfony.com/cli/v4.5.4/symfony_linux_amd64 -O /tmp/symfony.gz
RUN gzip -d /tmp/symfony.gz
RUN chmod 755 /tmp/symfony
RUN mv /tmp/symfony /usr/local/bin/symfony
RUN symfony security:check
CMD ["php", "runner.php"]

