FROM ghcr.io/violinist-dev/php-base:8.3-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY --from=ghcr.io/violinist-dev/built:8.3-multi-composer-2 /use/source/myapp/runner.phar /runner.phar

CMD ["/runner.phar"]
