FROM violinist/php-base:8.0-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN composer require bitbucket/client:^2 \
    && composer install --no-dev --optimize-autoloader \
    # Make sure our php is always used.
    && ln -s /usr/local/bin/php vendor/bin/php \
    && rm -rf /usr/local/bin/composer

CMD ["php", "runner.php"]
