FROM violinist/php-base:7.2-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

ENV COMPOSER_VERSION=2

RUN composer require composer/composer:^2 bitbucket/client:^2 --update-with-dependencies \
    && composer install --no-dev --optimize-autoloader \
    && rm -rf /usr/local/bin/composer

CMD ["php", "runner.php"]
