ARG COMPOSER_VERSION
ARG PHP_VERSION

FROM ghcr.io/violinist-dev/built:${PHP_VERSION}-multi-composer-${COMPOSER_VERSION} as built

FROM ghcr.io/violinist-dev/php-base:8.3-multi
MAINTAINER eiriksm <eirik@morland.no>

ARG COMPOSER_VERSION
ARG PHP_VERSION

COPY --from=built /usr/src/myapp/runner.phar /runner.phar

RUN composer install --no-dev --optimize-autoloader \
    # Make sure our php is always used.
    && ln -s /usr/local/bin/php vendor/bin/php \
    && rm -rf /usr/local/bin/composer \
    && wget https://getcomposer.org/download/latest-2.x/composer.phar -O /tmp/composer \
    && chmod 755 /tmp/composer \
    && mv /tmp/composer /usr/local/bin/composer


CMD ["/runner.phar"]
