FROM violinist/php-base:7.2-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN composer install --no-dev --optimize-autoloader \
    && composer require bitbucket/client \
    && rm -rf /usr/local/bin/composer

CMD ["php", "runner.php"]
