FROM violinist/php-base:7.4-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

ENV COMPOSER_VERSION=2

RUN composer install --no-dev --optimize-autoloader && \
    composer require composer/composer:^2 bitbucket/client:^2 --update-with-dependencies \
    # Make sure our php is always used.
    && composer global remove hirak/prestissimo \
    && ln -s /usr/local/bin/php vendor/bin/php \
    && rm -rf /usr/local/bin/composer

CMD ["php", "runner.php"]
