FROM violinist/php-base:7.4-multi
MAINTAINER eiriksm <eirik@morland.no>

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN composer install --no-dev --optimize-autoloader && \
    composer require composer/composer:^1 --update-with-dependencies \
    && composer require bitbucket/client:^2 \
    # Make sure our php is always used.
    && ln -s /usr/local/bin/php vendor/bin/php \
    && rm -rf /usr/local/bin/composer

CMD ["php", "runner.php"]
